apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-deploy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sysdig-agent
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sysdig-deploy
    repoURL: https://charts.sysdig.com
    targetRevision: 1.66.0