apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-deploy
spec:
  destination:
    name: ''
    namespace: sysdig-agent
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - jsonPointers:
    - /data/js_server_password
    kind: Secret
    name: sysdig-agent-clusterscanner
  - group: apps
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1secret
    kind: Deployment
    name: sysdig-agent-clusterscanner
  sources:
  - repoURL: 'https://charts.sysdig.com'
    chart: sysdig-deploy
    targetRevision: 1.66.0
    helm:
      valueFiles:
      - $values/common/common-clustersheild-values.yaml
      - $values/prod/prod-cluster1-values.yaml
  - repoURL: 'https://github.com/andrewd-sysdig/argocd-sysdig-example.git'
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true