global:
  sysdig:
     accessKeySecret: sysdig-agent # Access Key Secret - from <sysdig URL>/secure/#/settings/agentInstallation
     region: au1
     secureAPITokenSecret: sysdig-api-token # API Token Secret - from <sysdig URL>/secure/#/settings/user
     tags:
       environment: CHANGE_ME
  clusterConfig:
     name: CHANGE_ME # Name of your cluster so Sysdig can identify it
  kspm:
      deploy: true # Enables KSPM, ie benchmarks for Kubernetes & Hosts
agent:
  enabled: true # Enables sysdig-agent which does Falco syscall Threat Detection, Activity Audit, Image Profiling, ML, Drift Detection etc...
  sysdig:
    settings:
      app_checks_enabled: false # Disable legacy appchecks for Sysdig Monitor
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 800Mi
nodeAnalyzer:
  enabled: true  # Enables Node Analyzer (Container/Host Runtime Vuln Scanning & KSPM Benchmarks)
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
  nodeAnalyzer:
    apiEndpoint: app.au1.sysdig.com # Set for your region
    benchmarkRunner:
      deploy: false # Disable old benchmark runner as replaced by KSPM
    runtimeScanner:
      settings:
        eveEnabled: true # Risk Spotlight/In Use
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100Mi
          memory: 2Gi
    hostScanner:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 512Mi
    kspmAnalyzer:
      resources:
        requests:
          cpu: 50m
          memory: 10Mi
        limits:
          cpu: 100m
          memory: 512Mi
admissionController:
  enabled: true # Used for Kubernetes Audit Log Threat Detection
  scanner:
    enabled: false # Don't need on deployment scanning enforcement (legacy engine)
  webhook:
    hostNetwork: false  # Set this to true if using a custom CNI where the managed control plane nodes are unable to initiate network connections to the pods
    autoscaling:
      minReplicas: 1
rapidResponse:
  enabled: false
